name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  init:
    runs-on: macos-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3

      # Installing the NodeJS version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Installing project dependencies
      - name: Installing project dependencies
        run: npm install

      # We are building the project in a Build build for the future tested
      - name: Build project
        run: npm run build:prod

        # Building the Storybook project
      - name: Building Storybook
        run: npm run storybook:build

        # Running Storybook Tests
      - name: Run Screenshot Test
        run: npm run test:screenshot:ci

        # Tests to verify compliance with the rules described in ESLint
        if: always()
      - name: Run linting for TS/TSX code
        run: npm run lint:ts

        # Tests to verify compliance with the rules described in Stylelin
        if: always()
      - name: Run linting for SCSS code
        run: npm run lint:scss

        # Running Unit Tests
        if: always()
      - name: Run init tests
        run: npm run test:unit
