name: GitHub Actions
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  linting:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Installing project dependencies
      - name: Installing project dependencies
        run: npm install

        # Tests to verify compliance with the rules described in ESLint
        if: always()
      - name: Run linting for TS/TSX code
        run: npm run lint:ts

        # Tests to verify compliance with the rules described in Stylelin
        if: always()
      - name: Run linting for SCSS code
        run: npm run lint:scss

  init-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Installing project dependencies
      - name: Installing project dependencies
        run: npm install

      # Running Unit Tests
      - name: Run init tests
        run: npm run test:unit

  screenshot-test:
    runs-on: macos-latest

    strategy:
      matrix:
        node: [16.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      # Installing project dependencies
      - name: Installing project dependencies
        run: npm install

      # We are building the project in a Build build for the future tested
      - name: Build project
        run: npm run build:prod

        # Building the Storybook project
      - name: Building Storybook
        run: npm run storybook:build

      # Running Storybook Tests
      - name: Run Screenshot Test
        run: npm run test:screenshot:ci
